# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 403d8415ba0e1266b42131df15604ff8ed0c59620be7fc10425e5038399fca3496ee96e44de74fd43161a511cb139820441766aa9719b69f6c3c266492c101f3

test:
  secret_key_base: 85122d57afdda27d924cb3bc129049fad9683cbaf80ec667adcbf4f9dd67a26baddc2b37a48b4eac781e1a08925af1ddd3f9a4ab99dfb263ceb09e6d1d2df412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
